Fatec.Treinamento.Web/Controllers/AdminTrilhasController.cs
using Fatec.Treinamento.Data.Repositories;
using Fatec.Treinamento.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Fatec.Treinamento.Web.Models;

namespace Fatec.Treinamento.Web.Controllers
{
    // Obs: Colocando o atributo [Authorize] no controller, garante que todas as actions so podem ser
    // acessadas quando o usuário estiver autorizado a utilizar.
    // Quando informo o parametro "Roles", indico que só quem tiver o perfil administrador poderá acessar.

    [Authorize(Roles="Administrador")]
    public class AdminTrilhasController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            var repo = new TrilhaRepository();

            var lista = repo.Listar();

            return View(lista);
        }

        [HttpGet]
        public ActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar(Trilha trilha)
        {
            using (var repo = new TrilhaRepository())
            {
                var inserido = repo.Inserir(trilha);

                if (inserido.Id == 0)
                {
                    ModelState.AddModelError("", "Erro");
                }

            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            using (var repo = new TrilhaRepository())
            {
                var trilha = repo.Obter(id);

                return View(trilha);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Trilha trilha)
        {
            using (var repo = new TrilhaRepository())
            {
                trilha = repo.Atualizar(trilha);

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult Excluir(int id)
        {
            using (var repo = new TrilhaRepository())
            {
                var trilha = repo.Obter(id);

                return View(trilha);
            }
        }

        [HttpPost]
        public ActionResult Excluir(Trilha trilha)
        {
            using (var repo = new TrilhaRepository())
            {
                repo.Excluir(trilha);

                return RedirectToAction("Index");
            }
        }

        [HttpGet]
        public ActionResult VincularCursos(int id)
        {
            // Essa view precisa dos dados da trilha para exibir o nome da trilha,
            // + uma lista com todos os cursos disponíveis e também uma outra lista
            // com os cursos que já estão selecionados.
            // Por isso criamos esse viewmodel para devolver isso tudo para a view;

            var model = new VincularCursosTrilhaViewModel();

            // Obtenho a Trilha
            using (var repo = new TrilhaRepository())
            {
                model.Trilha = repo.Obter(id);
            }

            // Monto a lista com os Itens selecionados:
            model.CursosSelecionados = model.Trilha.Cursos.Select(c => c.Id).ToList();
            
            // Obs. A sintaxe acima se chama Lambda, e é usada para montar uma lista de IDs que é o que
            // o Helper precisa pra montar um ListBox de multipla seleção.
            // Poderia ser feito um FOREACH para obter essa lista.
            

            // Lista com todos os cursos
            using (var repo = new CursoRepository())
            {
                var lista = repo.ListarCursosDetalhes();

                // transforma os itens da lista nos itens para vincular com a tela:
                // Obs: Esse foreach é desnecessário. Poderia ser resolvido com 1 única linha de lambda, porém
                // usei o for para ser mais fácil de entender.
                foreach (var curso in lista)
                {
                    var item = new SelectListItem
                    {
                        Text = curso.Nome,
                        Value = curso.Id.ToString()
                    };
                    model.CursosDisponiveis.Add(item);
                }
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult VincularCursos(VincularCursosTrilhaViewModel model)
        {
            // Aqui eu salvo os cursos vinculados.
            // No model, vai receber os IDs dos itens selecionados, entao é só 
            // passar isso pro método do repositório que faz a atualização.

            using (var repo = new TrilhaRepository())
            {
                repo.AtualizarCursos(model.Trilha.Id, model.CursosSelecionados.ToArray());
            }

            return RedirectToAction("Index");

        }
    }
}

Fatec.Treinamento.Web/Controllers/CursoController.cs
using Fatec.Treinamento.Data.Repositories;
using Fatec.Treinamento.Model.DTO;
using System;
using System.Collections.Generic;
using System.Data.Odbc;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fatec.Treinamento.Web.Controllers
{
    public class CursoController : Controller
    {

        [HttpGet]
        public ActionResult Index()
        {
            IEnumerable<DetalhesCurso> lista = new List<DetalhesCurso>();

            using (CursoRepository repo = new CursoRepository())
            {
                lista = repo.ListarCursos();
            }

            return View(lista);
        }

        [HttpGet]
        public ActionResult Assunto(int id)
        {
            IEnumerable<DetalhesCurso> lista = new List<DetalhesCurso>();

            using (CursoRepository repo = new CursoRepository())
            {
                lista = repo.ListarCursosPorAssunto(id);
            }

            return View(lista);
        }

        [HttpGet]
        public ActionResult Populares()
        {
            IEnumerable<DetalhesCurso> lista = new List<DetalhesCurso>();

            using (CursoRepository repo = new CursoRepository())
            {
                lista = repo.ListarCursos();

                // Pega apenas os 5 melhores ordenados pela classificação:
                lista = (from x in lista
                    orderby x.Classificacao descending
                    select x).Take(5).ToList();

            }

            return View(lista);
        }


        public ActionResult Pesquisar(string txtPesquisaCurso)
        {
            IEnumerable<DetalhesCurso> lista = new List<DetalhesCurso>();

            using (CursoRepository repo = new CursoRepository())
            {
                lista = repo.ListarCursosPorNome(txtPesquisaCurso);
            }

            return View(lista);
        }

        [HttpGet]
        public ActionResult Detalhes(int id)
        {
            using (CursoRepository repo = new CursoRepository())
            {
                var curso = repo.ObterDetalhesCurso(id);
                return View(curso);
            }
        }


        //get /curso/1/assistir/2
        [HttpGet]
        [Route("Curso/{idCurso}/Capitulo/{idCapitulo}/Video/{idVideo}", Name = "AssistirVideo")]   // ROTA CUSTOMIZADA
        public ActionResult Assistir(int idCurso, int idCapitulo, int idVideo)
        {
            using (CursoRepository repo = new CursoRepository())
            {
                var curso = repo.ObterDetalhesCurso(idCurso);

                // Vou devolver o ID do capítulo e video na viewbag.
                ViewBag.IdCapitulo = idCapitulo;
                ViewBag.IdVideo = idVideo;


                // pega o endereço do youtube do video que tem que rodar e devolve na viewbag tambem
                var cap = curso.Capitulos.FirstOrDefault(c => c.Id == idCapitulo);
                if (cap != null) 
                {
                    var vid = cap.Videos.FirstOrDefault(c => c.Id == idVideo);

                    if (vid != null)
                    {
                        ViewBag.CodigoYoutube = vid.CodigoYoutube;
                    }
                }

                return View(curso);
            }
        }
    }
}

Fatec.Treinamento.Web/Controllers/TreinamentoController.cs
using Fatec.Treinamento.Data.Repositories;
using Fatec.Treinamento.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Fatec.Treinamento.Web.Controllers
{
    public class TreinamentoController : Controller
    {
        
        [Authorize]
        public ActionResult Index()
        {

            int id = int.Parse(User.Identity.GetUserId());
            
            return View();
        }
    }
}

Fatec.Treinamento.Web/Controllers/UsuarioController.cs
using Fatec.Treinamento.Data.Repositories;
using Fatec.Treinamento.Model;
using Fatec.Treinamento.Model.Enum;
using Fatec.Treinamento.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;

using Microsoft.Owin.Host.SystemWeb;

namespace Fatec.Treinamento.Web.Controllers
{
    public class UsuarioController : Controller
    {
        
        [AllowAnonymous]
        [HttpGet]
        public ActionResult Registrar()
        {

            RegistroUsuarioViewModel model = new RegistroUsuarioViewModel();

            using (var repo = new PerfilRepository())
            {
                var lista = repo.Listar();
                model.ListaPerfil = (from x in lista
                    select new SelectListItem
                    {
                        Text = x.Nome,
                        Value = x.Id.ToString()
                    });
            }

            return View(model);

        }
        
        
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar(RegistroUsuarioViewModel model)
        {
            if (ModelState.IsValid)
            {
                var usuario = new Usuario
                {
                    Nome = model.Nome,
                    Email = model.Email,
                    Senha = model.Senha,
                    Ativo = true,
                    Perfil = new Perfil { Id = (int)TipoPerfil.Usuario } // Por padrão todos que se registram são usuarios.
                };
                
                using(UsuarioRepository repo = new UsuarioRepository())
                {
                    usuario = repo.Inserir(usuario);
                }
                    
                if (usuario.Id > 0)
                {
                    //TODO: logar o usuario
                    return RedirectToAction("Index", "Home");
                }
                
            }

            // Se chegou aqui, temos um problema. Devolvo o model para o form novamente.
            return View(model);
        }

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Usuario usuario;

            using (UsuarioRepository repo = new UsuarioRepository())
            {
                usuario = repo.Login(model.Email, model.Senha);
            }

            // Login com sucesso
            if (usuario != null)
            {
                var ident = new ClaimsIdentity(
                    new[]
                    {
                        // Padrão para utilzar o mecanismo antiforgery
                        new Claim(ClaimTypes.NameIdentifier, usuario.Id.ToString()),
                        new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider",
                            "ASP.NET Identity", "http://www.w3.org/2001/XMLSchema#string"),

                        // Outras Claims

                        // Nome do Usuario
                        new Claim(ClaimTypes.Name, usuario.Nome),

                        // Perfil
                        new Claim(ClaimTypes.Role, usuario.Perfil.Nome),

                        // Email
                        new Claim(ClaimTypes.Email, usuario.Email),

                    },
                    DefaultAuthenticationTypes.ApplicationCookie);

                HttpContext.GetOwinContext().Authentication.SignIn(
                    new AuthenticationProperties {IsPersistent = false}, ident);

                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                return RedirectToAction("Index", "Home");

            }
            else
            {
                ModelState.AddModelError("", "Credenciais Inválidas.");
                return View(model);
            }
            
        }

        public ActionResult LogOff()
        {
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            authenticationManager.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Fatec.Treinamento.Web/Views/Shared/ItensMenuAssuntos.cshtml
@model IEnumerable<Fatec.Treinamento.Model.DTO.CursosPorAssunto>

<li>@Html.ActionLink("Todos os cursos", "Index", "Curso")</li>
<li role="separator" class="divider"></li>
<li class="dropdown-header">ASSUNTOS</li>
@foreach (var item in Model)
{
    <li>@Html.ActionLink(item.Nome + " (" + item.TotalCursos + ")", "Assunto", "Curso", new { Id = item.Id }, null) </li>
}

Fatec.Treinamento.Web/Views/Shared/ListagemCursos.cshtml
@model IEnumerable<Fatec.Treinamento.Model.DTO.DetalhesCurso>

@foreach (var item in Model)
{
    <hr style="margin-bottom: 30px;">
    <div class="row">
        <div class="col-lg-12">
            <h3>
                @Html.ActionLink(item.Nome, "Detalhes", "Curso", new { id = item.Id }, null)
            </h3>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-5">
            Assunto: @Html.DisplayFor(modelItem => item.Assunto)
        </div>
        <div class="col-lg-5">
            @for (int i = 0; i < item.Classificacao; i++)
            {
                <span class="glyphicon glyphicon-star estrela-classificacao"></span>
            }
        </div>

    </div>
    <div class="row">

        <div class="col-lg-5">
            Data de Criação: @item.DataCriacao.ToString("dd/MM/yyyy")

        </div>
        <div class="col-lg-5">
            Autor: @Html.DisplayFor(modelItem => item.Autor)
        </div>

    </div>

}

Fatec.Treinamento.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Fatec Treinamentos</title>
    @Styles.Render("~/Content/css")
    @RenderSection("styles", required: false)
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a class="navbar-brand " href='@Url.Action("Index","Home")'>
                    <span class="glyphicon glyphicon-education" aria-hidden="true"></span>
                    <span class="aoxo"><span class="a">&Delta;</span><span class="o">O</span><span class="x">X</span><span class="q">&#9744</span></span>
                </a>
            </div>
            <div class="navbar-collapse collapse">

                @using (Html.BeginForm("Pesquisar", "Curso", FormMethod.Post, new { @class = "navbar-form navbar-left home-search-form", role = "form" }))
                {
                    <div class="form-group">
                        <div class="input-group">
                            <input id="txtPesquisaCurso" name="txtPesquisaCurso" type="text" class="form-control" placeholder="Procurar Curso...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary btn-search" type="button"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                            </span>
                        </div>
                    </div>
                }

                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Populares", "Populares", "Curso")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Cursos <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            @{
                                Html.RenderAction("MenuAssuntos", "Home");
                            }
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Trilhas", "Trilhas", "Cursos")</li>

                    @if (Request.IsAuthenticated)
                    {
                        //Valida se o usuário é administrador e exibe o menu de administração.

                        if (this.User.IsInRole("Administrador"))
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li>@Html.ActionLink("Cursos", "Index", "AdminCursos", null, new { style = "text-decoration: line-through" })</li>
                                    <li>@Html.ActionLink("Trilhas", "Index", "AdminTrilhas")</li>
                                    <li>@Html.ActionLink("Assuntos", "Index", "AdminAssuntos")</li>
                                    <li>@Html.ActionLink("Usuários", "Index", "AdminUsuarios", null, new { style = "text-decoration: line-through" })</li>
                                </ul>
                            </li>
                        }
                    }
                </ul>

                @if (Request.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                <span class="glyphicon glyphicon-user"></span> &nbsp;&nbsp; @User.Identity.GetUserName() <span class="caret"></span>
                            </a>
                                
                            <ul class="dropdown-menu">
                                <li>@Html.ActionLink("Meus Treinamentos", "Index", "Treinamento", null, new { style = "text-decoration: line-through" })</li>
                                <li>@Html.ActionLink("Meus Pontos", "MeusPontos", "Usuario", null, new { style = "text-decoration: line-through" })</li>
                                <li role="separator" class="divider"></li>
                                <li>@Html.ActionLink("Sair", "LogOff", "Usuario")</li>
                            </ul>
                        </li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Entrar", "Login", "Usuario")</li>
                        <li class="active">@Html.ActionLink("Registrar", "Registrar", "Usuario")</li>
                    </ul>
                }

            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()

    </div>

    <footer class="footer">
        <div class="container">
            <p>&copy; @DateTime.Now.Year - Fatec/Viceri</p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>

</html>